version: 2
jobs:
  build:
    docker:
      - image: adoptopenjdk/openjdk11
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - run: ./gradlew clean build
      - run: gradle test
